spring:
    shardingsphere:
        sharding:
            tables:
                t_order:
                    actual-data-nodes: master$->{0..1}.t_order_$->{0..1}
                    database-strategy:
                        inline:
                            algorithm-expression: master$->{user_id % 2}
                            sharding-column: user_id
                    table-strategy:
                        inline:
                            algorithm-expression: t_order_$->{order_id % 2}
                            sharding-column: order_id
                t_user:
                    actual-data-nodes: master$->{0..1}.t_user_$->{0..1}
                    database-strategy:
                        inline:
                            algorithm-expression: master$->{user_id % 2}
                            sharding-column: user_id
                    table-strategy:
                        inline:
                            algorithm-expression: t_user_$->{user_code % 2}
                            sharding-column: user_code