spring:
    shardingsphere:
        sharding:
            tables:
                t_order:
                    actual-data-nodes: master$->{0..1}.t_order_$->{0..1}
                    database-strategy:
                        hint:
                          algorithm-class-name: com.feng.shardingspheretest.sharding.hint.HintShardingDatabaseAlgorithm
                    table-strategy:
                        hint:
                          algorithm-class-name: com.feng.shardingspheretest.sharding.hint.HintShardingTableAlgorithm