spring:
    shardingsphere:
        sharding:
            tables:
                t_order:
                    # 整个表达式最终的结果将会根据每个子表达式的结果进行笛卡尔组合。
                    actual-data-nodes: master$->{0..1}.t_order_$->{0..1}
                    database-strategy:
                        standard:
                            sharding-column: user_id
                            precise-algorithm-class-name: com.feng.shardingjdbctest.algorithm.standard.PreciseShardingDatabaseAlgorithm
                            range-algorithm-class-name: com.feng.shardingjdbctest.algorithm.standard.RangeShardingDatabaseAlgorithm #可选
                    table-strategy:
                        standard:
                            sharding-column: order_id
                            precise-algorithm-class-name: com.feng.shardingjdbctest.algorithm.standard.PreciseShardingTableAlgorithm
                            range-algorithm-class-name: com.feng.shardingjdbctest.algorithm.standard.RangeShardingTableAlgorithm #可选