spring:
    shardingsphere:
        sharding:
            tables:
                t_order:
                    actual-data-nodes: master$->{0..1}.t_order_$->{0..1}
                    database-strategy:
                        complex:
                            sharding-columns: order_id,user_id
                            algorithm-class-name: com.feng.shardingjdbctest.algorithm.complex.ComplexKeysShardingDatabaseAlgorithm
                    table-strategy:
                        complex:
                            sharding-columns: order_id,user_id
                            algorithm-class-name: com.feng.shardingjdbctest.algorithm.complex.ComplexKeysShardingTableAlgorithm